#version: '3.8'
#services:
#  tests:
#    build: .
#    depends_on:
#      chrome:
#        condition: service_healthy
#
#  chrome:
#    image: selenium/standalone-chrome:latest
#    shm_size: 2gb
#    ports:
#      - "4444:4444"
#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:4444/wd/hub/status" ]
#      interval: 5s
#      timeout: 10s
#      retries: 10
#
#
#
#    environment:
#      - SE_NODE_MAX_SESSIONS=4
#      - SE_NODE_OVERRIDE_MAX_SESSIONS=true


version: '3.8'
services:
  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 2gb
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4444/wd/hub/status"]
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 30s

  tests:
    build: .
    depends_on:
      chrome:
        condition: service_healthy
    volumes:
      - .:/app